FROM node:latest
 #create a directory
 RUN mkdir -p usr/src/bot
 WORKDIR /usr/src/bot

 #copy and install out bot

 COPY package.json /usr/src/bot
 RUN npm install 

 #copy the bot to the container
 COPY . /usr/src/bot

#command to start bot
 CMD ["node", "index.js"]